# Generated by Django 5.0.3 on 2024-05-08 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_tutorial_tutorial_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 14, 43, 18, 911299), verbose_name='date published'),
        ),
    ]
