# Generated by Django 5.0.3 on 2024-05-08 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_tutorial_tutorial_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 19, 5, 1, 876474), verbose_name='date published'),
        ),
    ]
